/* บ้านเราหมูกระทะ — language links, nav, hours
   Thai lives at /, English at /en/ (generated by tools/build_en.py). */
(function () {
  var C = window.SITE_CONFIG || {};
  var KEY = 'brm_lang';
  var PAGE = document.documentElement.lang === 'en' ? 'en' : 'th';
  window.SITE_LANG = PAGE;

  // ---- values from js/config.js (one place to edit) ----
  // <a data-cfg-href="LINE_URL">  -> href from config (static href is only a no-JS fallback)
  // <a data-cfg-href="A|B">       -> first non-empty of A, B
  // <span class="js-line-id">     -> LINE ID text
  document.querySelectorAll('[data-cfg-href]').forEach(function (a) {
    var keys = a.getAttribute('data-cfg-href').split('|');
    for (var i = 0; i < keys.length; i++) { var v = (C[keys[i]] || '').trim(); if (v) { a.href = v; break; } }
  });
  // No working LINE link yet: hide every LINE button (each one sits next to a Call button).
  // <html class="no-line"> is set in the HTML so nothing flashes; it comes off as soon as LINE_URL is set.
  document.documentElement.classList.toggle('no-line', !(C.LINE_URL || '').trim());
  if (C.LINE_ID) document.querySelectorAll('.js-line-id').forEach(function (el) { el.textContent = C.LINE_ID; });

  // ---- booking mode: LINE card while BOOKING_API_URL is empty; real form once it is set ----
  // (?booking=test previews the form in test mode: nothing is sent, clearly labelled)
  var live = !!(C.BOOKING_API_URL || '').trim(), test = !live && /[?&]booking=test\b/.test(location.search);
  document.documentElement.classList.toggle('booking-live', live || test);
  document.documentElement.classList.toggle('booking-test', test);

  // Old ?lang=en / ?lang=th links, from before /en/ existed.
  var q = new URLSearchParams(location.search).get('lang');
  if ((q === 'en' || q === 'th') && q !== PAGE) { location.replace(q === 'en' ? 'en/' : '../'); return; }

  // Opened from a folder (file://): "en/" and "../" would show a folder listing, so point the
  // language links (and any other folder link) at the index.html inside.
  if (location.protocol === 'file:') {
    document.querySelectorAll('a[hreflang]').forEach(function (a) {
      var h = a.getAttribute('href');
      if (h && /\/$/.test(h) && !/^[a-z]+:/i.test(h)) a.setAttribute('href', h + 'index.html');
    });
  }

  var t = document.getElementById('langToggle');
  if (t) t.addEventListener('click', function (e) {
    var a = e.target.closest('a[hreflang]');
    if (a) { try { localStorage.setItem(KEY, a.getAttribute('hreflang')); } catch (err) {} }
  });

  // hours from config (one place to edit)
  var hrs = (C.OPEN_TIME || '17:00') + '–' + (C.CLOSE_TIME || '22:00');
  document.querySelectorAll('.js-hours').forEach(function (el) { el.textContent = hrs; });

  // mobile nav
  var btn = document.getElementById('menuBtn'), nav = document.getElementById('nav');
  btn.addEventListener('click', function () {
    var open = nav.classList.toggle('open'); btn.setAttribute('aria-expanded', open);
  });
  nav.addEventListener('click', function (e) { if (e.target.tagName === 'A') { nav.classList.remove('open'); btn.setAttribute('aria-expanded', 'false'); } });

  document.getElementById('year').textContent = new Date().getFullYear();
})();
// hide the floating mobile bar while the booking form / LINE booking card is on screen (it never covers inputs or buttons)
(function () {
  var bar = document.getElementById('fabBar');
  var targets = [document.getElementById('booker'), document.querySelector('.line-book')].filter(Boolean);
  if (!bar || !targets.length || !('IntersectionObserver' in window)) return;
  var vis = new Map();
  var io = new IntersectionObserver(function (es) {
    es.forEach(function (e) { vis.set(e.target, e.isIntersecting && e.target.offsetParent !== null); });
    var any = false; vis.forEach(function (v) { any = any || v; });
    bar.classList.toggle('away', any && innerWidth < 960);
  }, { threshold: 0.15 });
  targets.forEach(function (t) { io.observe(t); });
})();
// Netlify's "Powered by Netlify" badge (injected by Netlify on free-plan sites, bottom-right) must never cover
// the mobile bar: when it's on the page, lift the bar above it. Turn the badge off in Netlify:
// Project configuration → General → Powered by Netlify badge.
(function () {
  var root = document.documentElement;
  function check() {
    var f = document.getElementById('nl-badge-frame') || document.getElementById('nl-hud-frame');
    root.classList.toggle('has-nl-badge', !!(f && f.isConnected && getComputedStyle(f).display !== 'none'));
  }
  check();
  if ('MutationObserver' in window) new MutationObserver(check).observe(document.body, { childList: true });
})();
// desktop: floating LINE button appears once the visitor scrolls past the hero
(function () {
  var f = function () { document.body.classList.toggle('scrolled', scrollY > 500); };
  addEventListener('scroll', f, { passive: true }); f();
})();
