/* บ้านเราหมูกระทะ — language links, nav, hours
   Thai lives at /, English at /en/ (generated by tools/build_en.py). */
(function () {
  var C = window.SITE_CONFIG || {};
  var KEY = 'brm_lang';
  var PAGE = document.documentElement.lang === 'en' ? 'en' : 'th';
  window.SITE_LANG = PAGE;

  // ---- values from js/config.js (one place to edit) ----
  // <a data-cfg-href="LINE_URL">  -> href from config (static href is only a no-JS fallback)
  // <a data-cfg-href="A|B">       -> first non-empty of A, B
  // <span class="js-line-id">     -> LINE ID text
  document.querySelectorAll('[data-cfg-href]').forEach(function (a) {
    var keys = a.getAttribute('data-cfg-href').split('|');
    for (var i = 0; i < keys.length; i++) { var v = (C[keys[i]] || '').trim(); if (v) { a.href = v; break; } }
  });
  // Empty LINE_URL: hide every LINE button (html.no-line). With LINE_URL set, buttons stay visible.
  document.documentElement.classList.toggle('no-line', !(C.LINE_URL || '').trim());
  if (C.LINE_ID) document.querySelectorAll('.js-line-id').forEach(function (el) { el.textContent = C.LINE_ID; });

  // ---- booking mode: LINE card while BOOKING_API_URL is empty; real form once it is set ----
  // (?booking=test previews the form in test mode: nothing is sent, clearly labelled)
  var live = !!(C.BOOKING_API_URL || '').trim(), test = !live && /[?&]booking=test\b/.test(location.search);
  document.documentElement.classList.toggle('booking-live', live || test);
  document.documentElement.classList.toggle('booking-test', test);

  // Old ?lang=en / ?lang=th links, from before /en/ existed.
  var q = new URLSearchParams(location.search).get('lang');
  if ((q === 'en' || q === 'th') && q !== PAGE) { location.replace(q === 'en' ? 'en/' : '../'); return; }

  // Opened from a folder (file://): "en/" and "../" would show a folder listing, so point the
  // language links (and any other folder link) at the index.html inside.
  if (location.protocol === 'file:') {
    document.querySelectorAll('a[hreflang]').forEach(function (a) {
      var h = a.getAttribute('href');
      if (h && /\/$/.test(h) && !/^[a-z]+:/i.test(h)) a.setAttribute('href', h + 'index.html');
    });
  }

  // Stay at the same spot when switching TH ↔ EN (hash of the section in view; fraction fallback).
  // Without JS the language links still just open / or /en/ — progressive enhancement only.
  var SCROLL_KEY = 'brm_lang_scroll';
  function nearestAnchorId() {
    // Skip sticky #top — it always sits under the probe. Prefer the section that
    // currently owns a point just under the header; #noodles (inside #menu) wins by
    // being the innermost match. Fall back to #top only near the true page top.
    var els = document.querySelectorAll('section[id], #noodles');
    var probe = Math.min(140, Math.max(64, innerHeight * 0.2));
    var best = '', bestH = Infinity;
    for (var i = 0; i < els.length; i++) {
      var el = els[i], id = el.id;
      if (!id) continue;
      var r = el.getBoundingClientRect();
      if (r.top <= probe && r.bottom > probe + 40) {
        if (r.height < bestH) { bestH = r.height; best = id; }
      }
    }
    if (best) return best;
    if (scrollY < 100) return 'top';
    var near = '', dist = Infinity;
    for (var j = 0; j < els.length; j++) {
      var el2 = els[j], r2 = el2.getBoundingClientRect();
      if (r2.bottom < 0 || r2.top > innerHeight) continue;
      var d = Math.abs(r2.top - probe);
      if (d < dist) { dist = d; near = el2.id; }
    }
    return near;
  }
  function scrollToId(id) {
    var el = document.getElementById(id);
    if (!el) return;
    var header = document.getElementById('top');
    var pad = header ? Math.min(header.offsetHeight + 8, 120) : 70;
    var y = el.getBoundingClientRect().top + scrollY - pad;
    scrollTo(0, Math.max(0, Math.round(y)));
  }
  function settle(fn) {
    fn();
    addEventListener('load', fn);
    setTimeout(fn, 50);
    setTimeout(fn, 300);
    setTimeout(fn, 1000);
    setTimeout(fn, 2000);
    document.querySelectorAll('img').forEach(function (img) {
      if (!img.complete) img.addEventListener('load', fn, { once: true });
    });
    if ('ResizeObserver' in window) {
      var ro = new ResizeObserver(fn);
      ro.observe(document.documentElement);
      setTimeout(function () { try { ro.disconnect(); } catch (e) {} }, 2500);
    }
  }
  // Re-pin #hash after images/fonts shift the layout (language switch and ordinary deep links).
  (function pinHash() {
    var id = (location.hash || '').replace(/^#/, '');
    if (!id || !document.getElementById(id)) return;
    settle(function () { scrollToId(id); });
  })();
  (function restoreLangScroll() {
    try {
      var raw = sessionStorage.getItem(SCROLL_KEY);
      if (raw == null) return;
      sessionStorage.removeItem(SCROLL_KEY);
      if (location.hash) return; // #section from the click path wins
      var f = parseFloat(raw);
      if (!(f >= 0) || f > 1.05) return;
      var go = function () {
        var max = Math.max(1, Math.max(document.documentElement.scrollHeight, document.body.scrollHeight) - innerHeight);
        scrollTo(0, Math.round(Math.min(1, f) * max));
      };
      settle(go);
    } catch (err) {}
  })();

  var t = document.getElementById('langToggle');
  if (t) t.addEventListener('click', function (e) {
    var a = e.target.closest('a[hreflang]');
    if (!a) return;
    var dest = a.getAttribute('hreflang');
    try { localStorage.setItem(KEY, dest); } catch (err) {}
    if (dest === PAGE) return;
    var base = (a.getAttribute('href') || '').split('#')[0];
    var id = nearestAnchorId();
    if (id) {
      a.setAttribute('href', base + '#' + id);
    } else {
      try {
        var max = Math.max(1, Math.max(document.documentElement.scrollHeight, document.body.scrollHeight) - innerHeight);
        sessionStorage.setItem(SCROLL_KEY, String(scrollY / max));
      } catch (err) {}
      if (base) a.setAttribute('href', base);
    }
  });

  // hours from config (one place to edit)
  var hrs = (C.OPEN_TIME || '17:00') + '–' + (C.CLOSE_TIME || '22:00');
  document.querySelectorAll('.js-hours').forEach(function (el) { el.textContent = hrs; });

  // mobile nav
  var btn = document.getElementById('menuBtn'), nav = document.getElementById('nav');
  btn.addEventListener('click', function () {
    var open = nav.classList.toggle('open'); btn.setAttribute('aria-expanded', open);
  });
  nav.addEventListener('click', function (e) { if (e.target.tagName === 'A') { nav.classList.remove('open'); btn.setAttribute('aria-expanded', 'false'); } });

  document.getElementById('year').textContent = new Date().getFullYear();
})();
// hide the floating mobile bar while the booking form / LINE booking card is on screen (it never covers inputs or buttons)
(function () {
  var bar = document.getElementById('fabBar');
  var targets = [document.getElementById('booker'), document.querySelector('.line-book')].filter(Boolean);
  if (!bar || !targets.length || !('IntersectionObserver' in window)) return;
  var vis = new Map();
  var io = new IntersectionObserver(function (es) {
    es.forEach(function (e) { vis.set(e.target, e.isIntersecting && e.target.offsetParent !== null); });
    var any = false; vis.forEach(function (v) { any = any || v; });
    bar.classList.toggle('away', any && innerWidth < 960);
  }, { threshold: 0.15 });
  targets.forEach(function (t) { io.observe(t); });
})();
// Netlify's "Powered by Netlify" badge (injected by Netlify on free-plan sites, bottom-right) must never cover
// the mobile bar: when it's on the page, lift the bar above it. Turn the badge off in Netlify:
// Project configuration → General → Powered by Netlify badge.
(function () {
  var root = document.documentElement;
  function check() {
    var f = document.getElementById('nl-badge-frame') || document.getElementById('nl-hud-frame');
    root.classList.toggle('has-nl-badge', !!(f && f.isConnected && getComputedStyle(f).display !== 'none'));
  }
  check();
  if ('MutationObserver' in window) new MutationObserver(check).observe(document.body, { childList: true });
})();
// desktop: floating LINE button appears once the visitor scrolls past the hero
(function () {
  var f = function () { document.body.classList.toggle('scrolled', scrollY > 500); };
  addEventListener('scroll', f, { passive: true }); f();
})();
