/* บ้านเราหมูกระทะ — language, nav, hours
   Thai lives at /, English at /en/ (generated by tools/build_en.py). */
(function () {
  var C = window.SITE_CONFIG || {};
  var KEY = 'brm_lang';
  var PAGE = document.documentElement.lang === 'en' ? 'en' : 'th';
  window.SITE_LANG = PAGE;

  // Old ?lang=en / ?lang=th links, from before /en/ existed.
  var q = new URLSearchParams(location.search).get('lang');
  if ((q === 'en' || q === 'th') && q !== PAGE) { location.replace(q === 'en' ? '/en/' : '/'); return; }

  var t = document.getElementById('langToggle');
  if (t) t.addEventListener('click', function (e) {
    var a = e.target.closest('a[hreflang]');
    if (a) { try { localStorage.setItem(KEY, a.getAttribute('hreflang')); } catch (err) {} }
  });

  // hours from config (one place to edit)
  var hrs = (C.OPEN_TIME || '17:00') + '–' + (C.CLOSE_TIME || '22:00');
  document.querySelectorAll('.js-hours').forEach(function (el) { el.textContent = hrs; });

  // mobile nav
  var btn = document.getElementById('menuBtn'), nav = document.getElementById('nav');
  btn.addEventListener('click', function () {
    var open = nav.classList.toggle('open'); btn.setAttribute('aria-expanded', open);
  });
  nav.addEventListener('click', function (e) { if (e.target.tagName === 'A') { nav.classList.remove('open'); btn.setAttribute('aria-expanded', 'false'); } });

  document.getElementById('year').textContent = new Date().getFullYear();
})();
// hide the floating mobile bar while the booking form is on screen (so it never covers inputs)
(function () {
  var bar = document.getElementById('fabBar'), bk = document.getElementById('booker');
  if (!bar || !bk || !('IntersectionObserver' in window)) return;
  new IntersectionObserver(function (es) { es.forEach(function (e) { bar.classList.toggle('away', e.isIntersecting && innerWidth < 960); }); }, { threshold: 0.15 }).observe(bk);
})();
// desktop: floating LINE button appears once the visitor scrolls past the hero
(function () {
  var f = function () { document.body.classList.toggle('scrolled', scrollY > 500); };
  addEventListener('scroll', f, { passive: true }); f();
})();
